version: "3.2"
services:
  nba-frontend:
    container_name: nba-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
    command: npm start
  php:
    build: ./nba-backend/php/
    networks:
      - backend
    volumes:
      - ./nba-backend/public_html/:/var/www/html/
    container_name: php
    ports:
      - '3000:80'
  database:
    container_name: DB
    image: mariadb
    networks:
      - backend
    volumes:
       - ./nba-backend/mariadb/:/var/lib/mysql/
    ports:
      - '3308:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=admin123
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=123
        - MYSQL_DATABASE=npa
networks:
  frontend:
  backend:
