version: "3.2"
services:
  nba-frontend:
    container_name: nba-frontend
    build:
      context: ./nba-frontend
    command: npm run start
    networks:
      - backend
    volumes:
      - ./nba-frontend:/app
      - /app/node_modules
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
  nba-localapi:
    container_name: nba-localapi
    networks:
      - backend
    build:
      context: ./nba-localapi
    volumes:
      - ./nba-localapi:/app
      - /app/node_modules
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=development
    # wait until DB container start
    command: bash -c "sleep 5; npm run start" 

  php:
    build: ./nba-backend/php/
    networks:
      - backend
    volumes:
      - ./nba-backend/php/public_html/:/var/www/html/
    container_name: php
    ports:
      - '3000:80'
  database:
    container_name: DB
    image: mariadb
    networks:
      - backend
    volumes:
       - ./nba-backend/mariadb/:/var/lib/mysql/
    ports:
      - '3308:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=admin123
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=123
        - MYSQL_DATABASE=nba
networks:
  backend:
